apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: {{.Values.namespace}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exam-app
  template:
    metadata:
      labels:
        app: exam-app
    spec:
      containers:
      - name: {{.Chart.name}}
        image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
        ports:
            - containerPort: 8080
