apiVersion: v1
kind: Service
metadata:
  labels:
    app: exam-app
  name: example-app
  namespace: {{Value.namespace}}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: exam-app
  type: NodePort
